# Generated by Django 4.0 on 2022-07-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_quiz_numofquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='numOfQuestions',
        ),
    ]
