# Generated by Django 4.0 on 2022-07-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_remove_quiz_numofquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='quiz',
        ),
    ]
