# Generated by Django 4.0 on 2022-07-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_remove_questions_quiz_delete_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='QuesModel',
        ),
    ]
